In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

In [3]:
# Arithmetic operations

# Add (size of both array must be same)
print(arr1 + arr2)

[ 7  9 11 13 15]


In [4]:
# Subtract (size of both array must be same)
print(arr2 - arr1)

[5 5 5 5 5]


In [5]:
# Multiply (size of both array must be same)
print(arr1 * arr2)

[ 6 14 24 36 50]


In [6]:
# Divide (size of both array must be same)
print(arr2 / arr1)

[6.         3.5        2.66666667 2.25       2.        ]


In [7]:
# Floor division (size of both array must be same)
print(arr2 // arr1)

[6 3 2 2 2]


In [8]:
# Exponent (size of both array must be same)
print(arr2 ** arr1)

[     6     49    512   6561 100000]


In [10]:
# Broadcasting
print(arr1 + 10) # Add 10 to all elements of arr1
print(arr2 - 5) # Subtract 5 from all elements of arr2

[11 12 13 14 15]
[1 2 3 4 5]


In [13]:
# Broadcasting in 2-d array
arr3 = np.arange(1,21).reshape(4,5)
print(arr3)
print(arr3 + 10)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [33]:
# Deep and Shallow copy
a = np.arange(1,11)
print(a)
shallow = a
print(shallow)
deep = a.copy()
print(deep)
slice = a[:6]
print(slice)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5 6]


In [34]:
a[0] = 11
print(a)
print(shallow)
print(deep)
print(slice) # in slice we have 11 , because in numpy slicing returns view, not a copy

[11  2  3  4  5  6  7  8  9 10]
[11  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[11  2  3  4  5  6]


In [36]:
slice[2] = 200 # this will give 200 in 2 index in shallow and a both because slice is view so change in slice will reflect in original array
a[1] = 100
print(a)
print(shallow)
print(deep)
print(slice)

[ 11 100 200   4   5   6   7   8   9  10]
[ 11 100 200   4   5   6   7   8   9  10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 11 100 200   4   5   6]
