In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [3]:
# Using boolean list
x = [True, False, False, True, True, False,True,True,False,True]
print(arr)
print(arr[x])

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  4  5  7  8 10]


In [4]:
# Using for loop and boolean array
y = []
for i in arr:
    if i <= 5:
        y.append(True)
    else:
        y.append(False)

print(arr)
print(y)
print(arr[y])


[ 1  2  3  4  5  6  7  8  9 10]
[True, True, True, True, True, False, False, False, False, False]
[1 2 3 4 5]


In [5]:
# Using numpy shortcut
filter1 = (arr > 6) & (arr < 10)
print(arr)
print(filter1)
print(arr[filter1])

filter2 = arr > 6
print(arr)
print(filter2)
print(arr[filter2])

[ 1  2  3  4  5  6  7  8  9 10]
[False False False False False False  True  True  True False]
[7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[False False False False False False  True  True  True  True]
[ 7  8  9 10]
