In [1]:
import numpy as np

In [2]:
# python lists
list1 = [1,2,3,4,5]
print(list1)

[1, 2, 3, 4, 5]


In [3]:
# python list can have elements of multiple data types
list2 = ['mudra', 1,2,3,0, True, False]
print(list2)

['mudra', 1, 2, 3, 0, True, False]


In [4]:
# access list element with index
print(list2[3])

3


In [5]:
# Numpy - Numeric Python
# ndarray - n-dimentional array
arr1 = np.array([1,2,3,4,5,6,7])
print(arr1)

[1 2 3 4 5 6 7]


In [19]:
# array attributes

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
# shape - return shape with dimention and elements per row
print(arr.shape)

# size - total number of elements in array
print(arr.size)

# dtype - return data type of the array elements
print(arr.dtype)

(3, 3)
9
int64


In [7]:
# arange - create numpy array (same as range)
arr2 = np.arange(10)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
# arange - (start, stop(not included), step)
arr3 = np.arange(0,10,3)
print(arr3)

[0 3 6 9]


In [9]:
# Zeros - create an array of zeros
arr4 = np.zeros(10)
print(arr4)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
# Multidimentional zeros (dimention, number of element in each dimention)
arr5 = np.zeros((3,10))
print(arr5)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [11]:
# full - create a multi-dimentional array with given values - (shape, fill_value, dtype = None, order = 'C')
arr6 = np.full([5,10],20,dtype=int)
print(arr6)

[[20 20 20 20 20 20 20 20 20 20]
 [20 20 20 20 20 20 20 20 20 20]
 [20 20 20 20 20 20 20 20 20 20]
 [20 20 20 20 20 20 20 20 20 20]
 [20 20 20 20 20 20 20 20 20 20]]


In [12]:
# access element in numpy array
print(arr6[0][9])

20


In [13]:
# python list to numpy array
list3 = [1,2,3,4,5]
arr7 = np.array(list3)
print(arr7)

[1 2 3 4 5]


In [14]:
# Ones - create an array of ones
arr8 = np.ones((3,10))
print(arr8)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [15]:
# linspace function (start,end(included),total_num_wanted)
# It'll return 7 evenly spaced numbers between 1-11 (included 1 and 11)
arr9 = np.linspace(1,11,7) 
print(arr9)

arr10 = np.linspace(0,1,60)
print(arr10)

[ 1.          2.66666667  4.33333333  6.          7.66666667  9.33333333
 11.        ]
[0.         0.01694915 0.03389831 0.05084746 0.06779661 0.08474576
 0.10169492 0.11864407 0.13559322 0.15254237 0.16949153 0.18644068
 0.20338983 0.22033898 0.23728814 0.25423729 0.27118644 0.28813559
 0.30508475 0.3220339  0.33898305 0.3559322  0.37288136 0.38983051
 0.40677966 0.42372881 0.44067797 0.45762712 0.47457627 0.49152542
 0.50847458 0.52542373 0.54237288 0.55932203 0.57627119 0.59322034
 0.61016949 0.62711864 0.6440678  0.66101695 0.6779661  0.69491525
 0.71186441 0.72881356 0.74576271 0.76271186 0.77966102 0.79661017
 0.81355932 0.83050847 0.84745763 0.86440678 0.88135593 0.89830508
 0.91525424 0.93220339 0.94915254 0.96610169 0.98305085 1.        ]
