In [1]:
import numpy as np

In [4]:
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])
print(matrix1)
print(matrix2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [5]:
# Matrix multiplication
ans = matrix1 @ matrix2 
# return 1*5+2*7 1*6+2*8
#        3*5+4*7 3*6+4*8
print(ans)

[[19 22]
 [43 50]]


In [6]:
# Matrix Multiplication using np.dot()
mult = np.dot(matrix1,matrix2)
print(mult)

[[19 22]
 [43 50]]


In [10]:
# Matrix transpose
transpose = matrix1.T
# rows becomes column
# 1 2    1 3
# 3 4    2 4
print(matrix1)
print(transpose)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
