In [2]:
#all imports
import numpy as np

In [3]:
#variables global
iterable_input = [1,2,3,4,5,6,7,8,9,0]

start = 0
stop = 50
step = 3
n = np.random.randint(2, 6) #array dimension
print(n)

5


# Basic array creation and shapes

In [9]:
#array_creation

#1) creting simple numpy array using iterable
basic_array = np.array(iterable_input)

#2) creating using range
range_array = np.arange(start, stop, step)

#3) creating array with zeros
zero_array = np.zeros(10)

# 3.1) zero array with different shift
zero_2d_array = np.zeros((n,10)) # here n is shape

#4) create array usiing full
array_using_full = np.full(shape= (n,8), fill_value=(np.random.random())*10)

In [10]:
#printing all arrays
print(basic_array)
print(range_array)
print(zero_array)
print(zero_2d_array)
print(array_using_full)

[1 2 3 4 5 6 7 8 9 0]
[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[3.23690066 3.23690066 3.23690066 3.23690066 3.23690066 3.23690066
  3.23690066 3.23690066]
 [3.23690066 3.23690066 3.23690066 3.23690066 3.23690066 3.23690066
  3.23690066 3.23690066]
 [3.23690066 3.23690066 3.23690066 3.23690066 3.23690066 3.23690066
  3.23690066 3.23690066]
 [3.23690066 3.23690066 3.23690066 3.23690066 3.23690066 3.23690066
  3.23690066 3.23690066]
 [3.23690066 3.23690066 3.23690066 3.23690066 3.23690066 3.23690066
  3.23690066 3.23690066]]


In [11]:
#shapes of array
print(basic_array.shape)
print(range_array.shape)
print(zero_array.shape)
print(zero_2d_array.shape)
print(array_using_full.shape)

(10,)
(17,)
(10,)
(5, 10)
(5, 8)


# slicing

In [12]:
# slicing is same as list
start_inclusive = 1
stop_exclusive = 5

print(basic_array[start_inclusive:stop_exclusive]) #slice
print(basic_array[(-start_inclusive):(-stop_exclusive)]) #invalid, returns empty
print(basic_array[(-stop_exclusive):(-start_inclusive)]) #slice from end
print(basic_array[(-start_inclusive):(-stop_exclusive):-1]) #reverse



[2 3 4 5]
[]
[6 7 8 9]
[0 9 8 7]


# Copy vs. View

In [21]:
#1) Create view
base_array = np.array(iterable_input)
np_view = base_array.view()

print(f'Original basic array {base_array}')
print(f'Original np_view {np_view}')

#make changes in base array
base_array[0] = 11

print(f'Changed base array {base_array}')
print(f'Original np_view {np_view}') #view is a real-time copy of base array all the time

# if you change a view, then it also changes the original array
np_view[0]=1

print(f'Original base array {base_array}')
print(f'Changed np_view {np_view}') #view is a real-time copy of base array all the time


Original basic array [1 2 3 4 5 6 7 8 9 0]
Original np_view [1 2 3 4 5 6 7 8 9 0]
Changed base array [11  2  3  4  5  6  7  8  9  0]
Original np_view [11  2  3  4  5  6  7  8  9  0]
Original base array [1 2 3 4 5 6 7 8 9 0]
Changed np_view [1 2 3 4 5 6 7 8 9 0]


In [ ]:
#2) Create a copy
np_copy = base_array.copy() #creates a snapshot of base array at the time of creation, after that it acts as a 2 seperate arrays

print(np_copy)

[1 2 3 4 5 6 7 8 9 0]
