In [83]:
import numpy as np

In [84]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])
print(data)

[[18 85 78]
 [19 92 88]
 [17 76 95]
 [18 65 70]
 [20 90 85]]


In [85]:
# Shape of the matrix
data.shape

(5, 3)

In [86]:
# Mean of age of all students
print(np.mean(data[:,0]))

18.4


In [87]:
# Math marks of all students
print(data[:,1])

[85 92 76 65 90]


In [88]:
#Find the highest Science mark
print(data[:,2].max())
# or
print(np.max(data[:,2]))

95
95


In [89]:
#Get details of the student who scored more than 90 in Math
data[data[:,1] > 90]

array([[19, 92, 88]])

In [90]:
#Increase Math marks of all students by 5
data[:,1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [91]:
#Find how many students are younger than 19
len(data[data[:,0] < 19])

3

In [92]:
#Calculate the average marks in each subject (column-wise mean)
np.mean(data[:,1:],0)

array([86.6, 83.2])

In [93]:
#Get data of students who scored at least 80 in both subjects
print(data[(data[:,1] >= 80) & (data[:,2] >= 80)])

[[19 97 88]
 [17 81 95]
 [20 95 85]]


In [98]:
#Replace all Science marks < 75 with 0
data[:,2][data[:,2] < 75] = 0 
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])