In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [3]:
# Slicing [start:end(not included):steps]
print(arr[0:5]) # Return 1,2,3,4,5

[1 2 3 4 5]


In [4]:
print(arr[0:5:2]) # Return 1,3,5

[1 3 5]


In [5]:
print(arr[::3]) # Return 1,4,7,10

[ 1  4  7 10]


In [6]:
# Not given end , it'll goes up until last element
print(arr[3:]) # Return 4,5,6,7,8,9,10

[ 4  5  6  7  8  9 10]


In [7]:
# give negative step it'll start from the end of the array
print(arr[::-1]) # Return reverse of the array

[10  9  8  7  6  5  4  3  2  1]


In [8]:
# Negative index 
print(arr[-3:-1]) # Return 8,9

[8 9]


In [9]:
# Negative start,end,step
print(arr[-2:-7:-1]) # Return 9,8,7,6,5

[9 8 7 6 5]


In [16]:
# Slicing in 2-d array
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [15]:
# pull slice of only 1st element
print(arr2[0:1,1:4]) # Return 2,3,4

[[2 3 4]
 [7 8 9]]


In [19]:
# pull slice of both element
print(arr2[0:,0:4]) # Return 1,2,3,4 6,7,8,9

[[1 2 3 4]
 [6 7 8 9]]


In [21]:
arr3 = np.arange(1,31).reshape(6,5)
print(arr3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [23]:
print(arr3[3:,3:])

[[19 20]
 [24 25]
 [29 30]]
