In [1]:
import numpy as np

In [2]:
num = np.array([1,4,3,7,9,6,8,2,5,0])
alpha = np.array(["cat","ox","dog","yak","cow","got","snak"])
boolean = np.array([True, False, True, False])

In [3]:
print(np.sort(num))
print(np.sort(alpha))
print(np.sort(boolean))

[0 1 2 3 4 5 6 7 8 9]
['cat' 'cow' 'dog' 'got' 'ox' 'snak' 'yak']
[False False  True  True]


In [4]:
arr = np.array([[2,7,4,9],[5,0,3,1]])
print(np.sort(arr))

[[2 4 7 9]
 [0 1 3 5]]
