In [1]:
import numpy as np

In [8]:
arr = np.arange(36).reshape(6,6)
print(arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [9]:
hsplit = np.hsplit(arr,2)
print(hsplit)
part1 = hsplit[0]
part2 = hsplit[1]
print(part1)
print(part2)

[array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20],
       [24, 25, 26],
       [30, 31, 32]]), array([[ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17],
       [21, 22, 23],
       [27, 28, 29],
       [33, 34, 35]])]
[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]
 [18 19 20]
 [24 25 26]
 [30 31 32]]
[[ 3  4  5]
 [ 9 10 11]
 [15 16 17]
 [21 22 23]
 [27 28 29]
 [33 34 35]]


In [11]:
vsplit = np.vsplit(arr,3)
print(vsplit)
vpart1 = vsplit[0]
vpart2 = vsplit[1]
vpart3 = vsplit[2]
print(vpart1)
print(vpart2)
print(vpart3)

[array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [12]:
a = np.hsplit(arr,6)
print(a)

[array([[ 0],
       [ 6],
       [12],
       [18],
       [24],
       [30]]), array([[ 1],
       [ 7],
       [13],
       [19],
       [25],
       [31]]), array([[ 2],
       [ 8],
       [14],
       [20],
       [26],
       [32]]), array([[ 3],
       [ 9],
       [15],
       [21],
       [27],
       [33]]), array([[ 4],
       [10],
       [16],
       [22],
       [28],
       [34]]), array([[ 5],
       [11],
       [17],
       [23],
       [29],
       [35]])]


In [14]:
b = np.vsplit(arr,6)
print(b)

[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]]), array([[18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29]]), array([[30, 31, 32, 33, 34, 35]])]
