In [1]:
import numpy as np

In [12]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr3 = np.array([11,12,13,14,15])
print(arr1)
print(arr2)
print(arr3)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [13]:
# Vertical stacking of aaray
# stack array in rows , only vectors are allowed in stacking(1-d array)
vstack = np.vstack((arr1, arr2,arr3))
print(vstack)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [14]:
# Horizontal stacking of array
# join arrays in one row
hstack = np.hstack((arr1,arr2,arr3))
print(hstack)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [15]:
# Column stacking of array
# add array in columns
column_stack = np.column_stack((arr1,arr2,arr3))
print(column_stack)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
