In [1]:
import numpy as np

In [32]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [33]:
r_sum = np.sum(s,1)
for i in r_sum:
    if i != 45:
        print('This is not a valid Sudoku')
        break
else:
    print('Valid for rows')

Valid for rows


In [34]:
c_sum = np.sum(s,0)
for i in c_sum:
    if i != 45:
        print('This is not a valid Sudoku')
        break
else:
    print('Valid for columns')

Valid for columns


In [36]:
isValidSudoku = True
for i in range(0,9,3):
    for j in range(0,9,3):
        slice = s[i:i+3,j:j+3]
        print(slice)

        if slice.sum() != 45:
            isValidSudoku = False
            break
    if not isValidSudoku:
      print('Not Valid Sudoku')
      break
else:
    print('Valid Sudoku')


[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]
Valid Sudoku
