In [4]:
import numpy as np

In [5]:
arr = np.array([0,1,4,9,16,25,36,49,64,81,100])
arr2 = np.array([-3,-2,-1,0,1,2,3])
arr3 = np.array([10,20,30,40,50])
arr4 = np.array([1,2,3,4,5])

In [6]:
# Square root
print(np.sqrt(arr))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [7]:
# Absolute
print(np.absolute(arr2))

[3 2 1 0 1 2 3]


In [8]:
# Exponent
print(np.exp(arr2))

[ 0.04978707  0.13533528  0.36787944  1.          2.71828183  7.3890561
 20.08553692]


In [9]:
# Min and Max
print(np.min(arr))
print(np.max(arr))

0
100


In [10]:
# Sign
print(np.sign(arr2))

[-1 -1 -1  0  1  1  1]


In [11]:
# sin, cos, tan
print(np.sin(arr))
print(np.cos(arr))
print(np.tan(arr))

[ 0.          0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175
 -0.99177885 -0.95375265  0.92002604 -0.62988799 -0.50636564]
[ 1.          0.54030231 -0.65364362 -0.91113026 -0.95765948  0.99120281
 -0.12796369  0.30059254  0.39185723  0.77668598  0.86231887]
[ 0.          1.55740772  1.15782128 -0.45231566  0.30063224 -0.13352641
  7.75047091 -3.17290855  2.34786031 -0.81099442 -0.58721392]


In [12]:
# negative and positive
print(np.negative(arr2)) # will apply negative sign to every element
print(np.positive(arr2)) # will apply positive sign to every element

[ 3  2  1  0 -1 -2 -3]
[-3 -2 -1  0  1  2  3]


In [13]:
# add, subtract, multiply, divide, power, mod
print(np.add(arr3,arr4))
print(np.subtract(arr3,arr4))
print(np.multiply(arr3,arr4))
print(np.divide(arr3,arr4))
print(np.mod(arr3,arr4))

[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]
[0 0 0 0 0]


In [14]:
arr5 = [[1,2,3],[4,5,6],[7,8,9]]
print(arr5)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [15]:
# sum(arr, axis) 0 - vertical/column , 1 - horizontal/row 
sum = np.sum(arr5,0) 
print(sum)

[12 15 18]
